Added UI Offset settings to be able to move the overlays
C1rdec/Poe-Lurker pull request #369
Opened 2022-12-31 18:05 UTC by Pegoth

This is useful for centered UI or in case of black bars (e.g. super ultra wide monitors).

Added it to the Advanced tab, looks like this:

![image](https://user-images.githubusercontent.com/20708012/210152113-3c3f1d8f-64bb-4f7a-a664-79ce9fa2dee5.png)

---

Relevant issue: #366

2023-01-10 04:12 UTC, C1rdec requested changes
Thanks for your time :)

I would remove the `Reposition` method since `SetWindowPosition` will place the overlay.
We only need to trigger "SetWindowPosition" when the Settings are changed.

2023-01-10 04:12 UTC, C1rdec commented on src/Lurker.UI/ViewModels/ShellViewModel.cs
> +                    this._helpOverlay.Reposition();
We do not need to Reposition. I would remove this method.

We only need to trigger the window position "OnSettingsSave"

2023-01-10 07:42 UTC, Pegoth commented on src/Lurker.UI/ViewModels/ShellViewModel.cs
> +                    this._helpOverlay.Reposition();
I didn't see any obvious way to trigger SetWindowPosition, that is why I added the Reposition method.

2023-01-10 21:09 UTC, C1rdec commented
After thinking about it I will handle this on a lower level.
I will be able to detect the size of the black bar with the ratio and the window width.

2023-01-10 21:09 UTC, closed without merging

2023-01-10 21:10 UTC, C1rdec commented
Thanks alot for the PR I will code this tonight.

I'll keep you posted

2023-01-10 21:11 UTC, Pegoth commented
Don't forget about #366 (ultrawide settings in game). That would be fairly easy to detect with reading the games ini setting however.

2023-01-10 21:15 UTC, C1rdec commented
Can you point me out where I can enable this settings?

2023-01-10 21:19 UTC, Pegoth commented
![image](https://user-images.githubusercontent.com/20708012/211664274-08b2a07c-be8a-4fea-8967-36e364127c23.png)

and in the config it is called

```ini
[ui]
centre_widescreen_hud=true
```

2023-01-10 21:23 UTC, Pegoth commented
Also, just for reference, I have 5120x1440 resolution, and I have exactly 832 pixel black bar on either side of the screen.

2023-01-11 03:06 UTC, C1rdec commented
![image](https://user-images.githubusercontent.com/5436436/211708555-809d1cc2-c4bc-4f10-afa9-dda0f199646d.png)

2023-01-11 07:37 UTC, Pegoth commented
Just tested it and it seems to be working.

2023-01-11 14:58 UTC, C1rdec commented
next step is the Centred UI option

2023-01-12 04:08 UTC, C1rdec commented
Yeah if you open the Stash the UI move... I think I will not add the support

![2023-01-11_22-42-25](https://user-images.githubusercontent.com/5436436/211973547-7422d895-6b1e-4a13-b663-6b9734e6b49f.gif)

2023-01-12 07:19 UTC, Pegoth commented
Ehh, didn't even notice it when I used it for a short while. Yeah, that would be hard to detect.